version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    groups:
      # Any updates not caught by the group config will get individual PRs
      gha-low-risk:
        update-types:
          - 'minor'
          - 'patch'
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    groups:
      update-playwright:
        patterns:
          - "playwright"
          - "@playwright/*"
      update-babel:
        patterns:
          - "babel-*"
          - "@babel/*"
    cooldown:
      default-days: 7
    ignore:
      # Prevent updates to ESM-only versions
      - dependency-name: 'log-symbols'
        versions: ['>=5.0.0']
      - dependency-name: 'chalk'
        versions: ['>=5.0.0']
