/**
 * Generates an exhaustive type-resolution fixture — one default deep-import per
 * component — so `verify:types` type-checks the `exports` `types` condition for
 * EVERY component, not just the hand-picked few in deep-imports.ts. Regenerated
 * on each `verify:types` run from the same component set the build and
 * verifyExports use (scripts/componentDirs.js), so a new component is covered
 * automatically. Output is git-ignored; do not edit it by hand.
 *
 * See dequelabs/cauldron#2465.
 */
const fs = require('fs');
const path = require('path');

const { componentDirEntries } = require('./componentDirs');

const { name: pkgName } = require('../package.json');
const COMPONENTS_ROOT = path.join(__dirname, '..', 'src', 'components');
const OUTPUT = path.join(
  __dirname,
  '..',
  'type-tests',
  'all-components.generated.ts'
);

const names = componentDirEntries(COMPONENTS_ROOT).map((entry) => entry.name);

const header =
  '// AUTO-GENERATED by scripts/genTypeTest.js — do not edit.\n' +
  '// Regenerated by `pnpm verify:types`. Asserts every component default\n' +
  '// deep-import resolves its types through the package exports map.\n';
const imports = names
  .map((name) => `import ${name} from '${pkgName}/${name}';`)
  .join('\n');
const body = `\n\nexport const allComponents = [\n${names
  .map((name) => `  ${name}`)
  .join(',\n')}\n];\n`;

fs.writeFileSync(OUTPUT, `${header}\n${imports}${body}`);
console.log(
  `genTypeTest: wrote ${names.length} component imports to ${OUTPUT}`
);
