name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Give us the details we need to see the bug.
      placeholder: Steps to reproduce the bug
      value: "Steps to reproduce"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see!
      value: "Not a bug."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Tell us what you are experiencing!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of cauldron did this happen with?
      placeholder: 4.0.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you experiencing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else we should know?
      description: Please provide any additional information that may be helpful.
      value: "Additional information"
