name: 'Dependencies'
description: 'Installs and builds dependencies for Cauldron'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: '**/yarn.lock'
    - run: yarn ci