import Head from 'next/head';
import { ReactElement } from 'react';
import SidebarLayout from './SidebarLayout';
import TopbarLayout from './TopbarLayout';
import styles from '../styles/Home.module.css';
import { Workspace } from '@deque/cauldron-react';
import Footer from './Footer';

type LayoutProps = {
  children: ReactElement;
};

const Layout = ({ children }: LayoutProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopbarLayout />
      <SidebarLayout />
      <Workspace id="main-content" tabIndex={-1}>
        <main className={styles.main}>{children}</main>
      </Workspace>
      <Footer>Test</Footer>
    </div>
  );
};

Layout.displayName = 'Layout';
export default Layout;
