name: 'Dependencies'
description: 'Installs and builds dependencies for Cauldron'
inputs:
  packages-react:
    type: boolean
    default: false
  packages-styles:
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: '**/yarn.lock'
    - name: Install root dependencies
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Install packages/react dependencies
      run: yarn install --cwd packages/react --frozen-lockfile
      shell: bash
      if: ${{ inputs.packages-react == 'true' }}
    - name: Install packages/styles dependencies
      run: yarn install --cwd packages/styles --frozen-lockfile
      shell: bash
      if: ${{ inputs.packages-styles == 'true' }}