name: Create Release PR

on:
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
      - uses: ./.github/actions/dependencies
      - name: Release
        run: pnpm run release
        env:
          COMMIT_BODY_HEADER: ":robot: This PR is created automatically ([see releasing](../blob/develop/RELEASING.md)) \n\n"
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_PAT }}
