name: Create Release PR

# on: [workflow_dispatch]
on:
  push:

jobs:
  create_release:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - id: release
        run: yarn run release
        env:
          COMMIT_BODY_HEADER: 'This PR was opened by a robot :robot: :tada: \n\n'