name: Monthly issue metrics
on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of the previous month
          first_day=$(date -d "-6 month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$first_day -6 month -1 day" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "$first_day..$last_day"
          echo "start_date=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:dequelabs/cauldron is:pr created:${{ env.start_date } -author:app/dependabot feat OR fix in:title'