name: Sync master/develop branches

on:
  push:
    branches:
      - master

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: dequelabs/action-sync-branches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "chore: merge master into develop"
          pr-body: "Remember to _merge_ (rather than squash) this PR!"
          pr-reviewers: schne324,scurker,stephenmathieson
          head: master
