name: Update Browserslist Database

on:
  schedule:
    # run on the 1st of every month
    - cron: '15 3 1 * *'
  workflow_call:
  workflow_dispatch:

jobs:
  update-browserlist-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: Update Browserlist Database
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          pnpm dlx update-browserslist-db@latest
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          add-paths: |
            pnpm-lock.yaml
          commit-message: 'chore: update browserlist database'
          branch: update-browserlist-database
          base: develop
          title: 'chore: update browserlist database'
          body: |
            This patch updates any outdated browserlist databases.
            This PR was opened automatically by a robot :robot: :tada:
